spring:
  profiles:
    include: swagger
  main:
    allow-bean-definition-overriding: true
  data:
    mongodb:
      uri: mongodb://localhost:27017/
      database: myDb

clamav:
  host: localhost
  port: 3310
